import timer from "./modules/timer";
import menu from "./modules/menu";
import modal from "./modules/modal";
import calculator from "./modules/calculator";
import validationForms from "./modules/validationForms";
import validationEmail from "./modules/validationEmail";
import validationPhone from "./modules/validationPhone";
import slider from "./modules/slider";
import tabs from "./modules/tabs";
import calc from "./modules/calc";
import helperOne from "./modules/helperOne";
helperOne();
calc(3000);
validationForms();
tabs();
validationPhone();
validationEmail();
modal();
calculator();
timer("5 june 2023");
menu();
slider();